[tox]
envlist = py3, fmt, lint, type

[testenv]
usedevelop = True
deps =
    -rrequirements.txt
    pytest
    pytest-mock
commands = pytest tests

[testenv:fmt]
description = Auto-format code
deps = ruff
commands = 
    ruff format tuxemon tests
    ruff check --fix --unsafe-fixes tuxemon tests

[testenv:format]
description = Run Format
deps = ruff
commands = ruff format tuxemon tests

[testenv:lint]
description = Run linter
deps = ruff
commands = ruff check tuxemon tests

[testenv:type]
description = Run static type checks
deps = 
    mypy
    -rrequirements.txt
commands = mypy tuxemon
