#
# Tuxemon
# Copyright (C) 2014, William Edwards <shadowapex@gmail.com>,
#                     Benjamin Bean <superman2k5@gmail.com>
#
# This file is part of Tuxemon.
#
# Tuxemon is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Tuxemon is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Tuxemon.  If not, see <http://www.gnu.org/licenses/>.
#
# Contributor(s):
#
# William Edwards <shadowapex@gmail.com>
# Derek Clark <derekjohn.clark@gmail.com>
# Leif Theden <leif.theden@gmail.com>
#
# core.player
#

import logging

from tuxemon.core.npc import NPC

logger = logging.getLogger(__name__)


# Class definition for the player.
class Player(NPC):
    """ Object for Players.  WIP
    """

    def __init__(self, npc_slug):
        super().__init__(npc_slug)
        self.isplayer = True

        # Game variables for use with events
        self.game_variables = {}

        # Number of steps
        self.game_variables['steps'] = 0

    def move(self, time_passed_seconds):
        """ Move the player around the game world
            Increment the number of steps

        :param time_passed_seconds: A float of the time that has passed since the last frame.
            This is generated by clock.tick() / 1000.0.

        :type time_passed_seconds: Float
        """
        # TODO: this will also record involuntary steps.
        # refactor so that only movements from the player are recorded.
        before_x = self.tile_pos[0]
        before_y = self.tile_pos[1]

        NPC.move(self, time_passed_seconds)

        after_x = self.tile_pos[0]
        after_y = self.tile_pos[1]

        diff_x = abs(after_x - before_x)
        diff_y = abs(after_y - before_y)

        self.game_variables['steps'] += diff_x + diff_y
