os:
  - linux
    #- osx
language: python
python:
  - "2.7"
sudo: required 
# command to install dependencies
install:
  - ./.travis/install.sh
# command to run tests
script: nosetests
virtualenv:
  system_site_packages: true
