# SPDX-License-Identifier: GPL-3.0
# Copyright (c) 2014-2025 William Edwards <shadowapex@gmail.com>, Benjamin Bean <superman2k5@gmail.com>
from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from tuxemon.map.map import proj
from tuxemon.npc import NPC

if TYPE_CHECKING:
    from tuxemon.session import Session

logger = logging.getLogger(__name__)


# Class definition for the player.
class Player(NPC):
    """Object for Players. WIP."""

    def __init__(
        self,
        npc_slug: str,
        session: Session,
    ) -> None:
        super().__init__(npc_slug, session=session)
        self.is_player = True

    @classmethod
    def create(cls, session: Session, slug: str) -> Player:
        """Creates a player instance only if one doesn't already exist."""
        if not session.has_player():
            session.set_player(cls(slug, session))
        return session.player

    def update(self, time_delta: float) -> None:
        """
        Update the player movement around the game world.

        Increment the number of steps.

        Parameters:
            time_delta: A float of the time that has passed since
                the last frame. This is generated by clock.tick() / 1000.0.
        """
        # TODO: this will also record involuntary steps.
        # refactor so that only movements from the player are recorded.
        before = proj(self.position)

        super().update(time_delta)

        after = proj(self.position)

        diff_x = abs(after.x - before.x)
        diff_y = abs(after.y - before.y)

        # increases steps player
        self.steps += diff_x + diff_y

        if diff_x != 0 or diff_y != 0:
            self.steps += diff_x + diff_y

            if self.step_tracker.trackers:
                self.step_tracker.update_all(diff_x, diff_y)

            if self.monsters:
                for monster in self.monsters:
                    monster.steps += diff_x + diff_y
