name: Build Installer Windows

on:
  workflow_call:

jobs:
  flatpak:
    runs-on: windows-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
            # Version range or exact version of a Python version to use, using SemVer's version range syntax.
            python-version: '3.10'
            # The target architecture (x86, x64) of the Python interpreter.
            architecture: 'x64'

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Install cx-freeze
        run: python -m pip install cx-freeze pyyaml

      - name: Build
        run: |
          copy buildconfig/setup_cx_freeze.py setup_cx_freeze.py
          copy buildconfig/build_config.yaml build_config.yaml
          python setup_cx_freeze.py build

      - name: Install NSIS
        run: |
          choco install nsis -y
          $nsisPath = "${env:ProgramFiles(x86)}\NSIS"
          echo "$nsisPath" | Out-File -Append $env:GITHUB_PATH

      - name: Check NSIS availability
        run: where makensis.exe

      - name: Build Installer
        run: |
          cd buildconfig
          cmd.exe /c "build_installer.bat"
          mkdir ../dist/
          Move-Item tuxemon-installer.exe ../dist/

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
            name: tuxemon_windows_installer
            path: dist
