name: Lint

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  workflow_call:
    inputs:
      RUN_LINT:
        required: false
        type: boolean
        default: false

jobs:
  lint:
    if: ${{ github.event.action == 'workflow_dispatch' || inputs.RUN_LINT == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          # Uncomment the following line to stop the build on errors
          # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
