name: Python Build & Test

on:
  workflow_call:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    with:
      RUN_LINT: false  # Linting is skipped

  python-app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python 3.10
      uses: actions/setup-python@v6
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: install as lib
      run: |
        pip install -e .
    - name: Test with pytest
      run: |
        pytest tests
